### PR TITLE
tfix: usage of validate and generate

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao <mashimiao.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by liangchenye** [comment]
:)   LGTM
PS: would you mind to fix a similar issue in generate.go ('generate a OCI..' ) thanks.

**Comment by Mashimiao** [comment]
fixed.

**Comment by liangchenye** [comment]
64decf7 LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
