### PR TITLE
SELinux: Fixup man page

### PR DESCRIPTION
**Pull request by rhatdan**
Man page does not show correctly.

Signed-off-by: Dan Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by wking** [comment]
4fcd94a1 looks good to me, although I'm also fine keeping the
*italics* around placeholders like *MOUNTLABEL*.

**Comment by wking** [comment]
While we're fixing these, --bind also has an ‘=[=’ synopsis.

**Comment by rhatdan** [comment]
Expanded the cleanup to add more consistency.  Most of the time we were not high lighting the option values, so I removed all highlights.

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
