### PR TITLE
Add support for using a base template

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by mrunalp** [comment]
@liangchenye @rhatdan PTAL

**Comment by liangchenye** [comment]
LGTM

**Comment by rhatdan** [comment]
Why not make the default template use this method and ship it separate from the runc implementation.

**Comment by mrunalp** [comment]
@rhatdan That would mean going elsewhere to get the first template. With this approach one can start by creating a template and then use it as the base for other templates.

**Comment by rhatdan** [comment]
How do I see the default template other then reading the code?  Can I easily generate the default template so I can edit it.

**Comment by mrunalp** [comment]
@rhatdan Just running ocitools generate will give you the default template.

**Comment by rhatdan** [comment]
Ok I guess we should document this, If you want to customize the default template, run ostree generate.  Edit config.json, or run ocitools to create a config.json, which you want as your customer "template."

**Comment by mrunalp** [comment]
Yeah, I will follow up with a PR with updated documentation.

**Pull request merged**
