### PR TITLE
Update runtime-spec dependency to v1.0.0-rc1

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by wking** [comment]
On Tue, Jun 14, 2016 at 02:14:49PM -0700, Mrunal Patel wrote:
>     M Godeps/Godeps.json (6)
>     M Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/config.go (76)
>     M Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/state.go (4)
>     M Godeps/_workspace/src/github.com/opencontainers/runtime-spec/specs-go/version.go (6)

This updates the config structures, but it doesn't update test_runtime
to use the newly-split create/start (opencontainers/runtime-spec#384).
Are we going to do that in a follow-up PR?  And we'll have to drop
Bash or insert something like [1] now that we need
PR_SET_CHILD_SUBREAPER to collect the container process's exit code
[2].

[1]: https://github.com/wking/oci-run
[2]: https://github.com/opencontainers/runtime-spec/pull/384#issuecomment-221772560

**Comment by mrunalp** [comment]
@wking Yes, we can do that change in a follow-on PR.

**Comment by liangchenye** [comment]
LGTM

**Comment by wking** [comment]
On Tue, Jun 14, 2016 at 03:42:04PM -0700, Mrunal Patel wrote:
> @wking Yes, we can do that change in a follow-on PR. 

In that cases there's not much chance of anything going wrong here,
since there were no backwards icompatible runtime-spec/specs-go
changes between 0.5.0 and 1.0.0-rc1.

**Comment by wking** [comment]
On Tue, Jun 14, 2016 at 02:14:49PM -0700, Mrunal Patel wrote:
>     M Godeps/Godeps.json (6)

This actually bumped to v1.0.0-rc1-15-g6de52a7, 15 commits after the
v1.0.0-rc1 tag.  Can we roll it back to the tag?  With the current
Godeps I'm still seeing #108:

  $ ./test_runtime.sh -r ccon-oci
  -----------------------------------------------------------------------------------
  VALIDATING RUNTIME: ccon-oci
  -----------------------------------------------------------------------------------
  …
  NotImplementedError: unsupported OCI-spec version: 1.0.0-rc1-dev
  Runtime ccon-oci failed validation

**Pull request merged**
