### PR TITLE
add bundle validate as sub-command

### PR DESCRIPTION
**Pull request by liangchenye**
Signed-off-by: liangchenye <liangchenye@huawei.com>

Clean the worthless commits in (https://github.com/opencontainers/ocitools/pull/4/) and re-submit it.

### CODE REVIEW

**Comment by mrunalp** [comment]
Thanks for the PR. I am on vacation and will be slow in responding till next week.

**Comment by liangchenye** [comment]
@mrunalp   bundle validate is update to 0.3.0
I also update generate.go to 0.3.0 in commit '0fbe252'.

**Comment by mrunalp** [comment]
Build failure as you need to bump up the spec to 0.3.0 in Godeps. Thanks!

**Comment by liangchenye** [comment]
Godeps updated.

The config.json generated by ocitools could not pass the bundle validation, since three security fields are not noted as 'optional', I submit a PR here (https://github.com/opencontainers/specs/pull/325)

**Comment by liangchenye** [comment]
Opps, the codes under cmd directory should also need to be changed.

**Comment by liangchenye** [comment]
cmd updated.

**Comment by mrunalp** [comment]
Can you update the deps to pickup the change where selinuxlabel and apparmor got moved to proces?

**Comment by mrunalp** [comment]
Also, we need to make seccomp optional in the spec. Otherwise this seems to be working well.

**Comment by mrunalp** [comment]
I have created PR for seccomp https://github.com/opencontainers/specs/pull/333

**Comment by mrunalp** [comment]
I think we can merge this for now and fix up things in follow up PRs. Thanks! LGTM

**Comment by liangchenye** [comment]
Yes, I'll update all of the selinuxlabel/apparmor/seccomp Godeps once `seccomp` PR checked in.
Thanks

**Pull request merged**
