### PR TITLE
generate: Remove superfluous err check from Save

### PR DESCRIPTION
**Pull request by wking**
Same as #160, but targeting v1.0.0.rc1.

### CODE REVIEW

**Comment by Mashimiao** [comment]
The fix seems good. But why just fix v1.0.0.rc1 not master?

**Comment by wking** [comment]
On Wed, Jul 27, 2016 at 10:46:20PM -0700, Ma Shimiao wrote:
> The fix seems good. But why just fix v1.0.0.rc1 not master?

So we can just merge v1.0.0.rc1 into master periodically to pull
v1.0.0-rc1-compatible changes forward instead of having to file all
these backport PRs [1].

[1]: https://github.com/opencontainers/ocitools/pull/140#issuecomment-234602988

**Comment by Mashimiao** [comment]
Got it. I just think it's a little wired. In my opinion, master should be the newest branch.

**Comment by wking** [comment]
On Wed, Jul 27, 2016 at 11:07:42PM -0700, Ma Shimiao wrote:
> Got it. I just think it's a little wired. In my opinion, master
> should be the newest branch.

Master *is* the newest branch.  I just think new commits should target
the *oldest* compatible branch first, and then we merge the old
branches forward into the newer branches (like Git does [1]).

[1]: https://git.kernel.org/cgit/git/git.git/tree/Documentation/SubmittingPatches?h=v2.9.2#n4

**Comment by mrunalp** [comment]
@wking While that approach sounds good for kernel development, I think that the github model that most developers are used to is submitting PRs to master and backporting to other stable branches.

**Comment by wking** [comment]
On Thu, Jul 28, 2016 at 04:05:58PM -0700, Mrunal Patel wrote:
> @wking While that approach sounds good for kernel development, I
> think that the github model that most developers are used to is
> submitting PRs to master and backporting to other stable branches.

It depends on who submits/reviews the v1.0.0.rc1 PRs.  I think there
will be less work total if folks PR v1.0.0.rc1 for
1.0.0-rc1-compatible changes, but there will be less work for initial
contributors if they PR master and leave it to someone else to
backport, PR, review, and merge the v1.0.0.rc1 version of their work.
And whether that backport work will get done depends on how seriously
maintainers take the v1.0.0.rc1 branch and minimizing the difference
between it and master (because a smaller difference means easier
sharing between the branches).

**Comment by mrunalp** [comment]
LGTM. But we'll need to get this into master later.

**Comment by wking** [comment]
On Tue, Aug 02, 2016 at 05:06:13PM -0700, Mrunal Patel wrote:
> LGTM. But we'll need to get this into master later. 

I'm setting up a merge from v1.0.0.rc1, but we'll need to catch
v1.0.0.rc1 up with master by backporting recent master work first.
#162 is part of that, and I've just filed #177, #178, and #179.  Once
we merge those into v1.0.0.rc1, we should be able to merge v1.0.0.rc1
without unnecessary conflicts.

**Pull request merged**
