### PR TITLE
validate: Improved version handling

### PR DESCRIPTION
**Pull request by wking**
Use an off-the-shelf SemVer parser and error out if the config targets
an unsupported spec version.  Slightly more detail in the commit
messages ;).

### CODE REVIEW

**Comment by wking** [comment]
It looks like I'm missing some Godeps magic.  Can anyone point me in the right direction?

**Comment by mrunalp** [comment]
@wking If you have `"github.com/blang/semver"` in your $GOPATH, then just run godep save after changing to ocitools directory. Your git diff should now show a change in Godeps.json to add this dependency and copy the files under Godeps/_workspace.

**Comment by wking** [comment]
On Fri, Jun 03, 2016 at 04:35:01PM -0700, Mrunal Patel wrote:
> … just run godep save …

Thanks.  Added with 629e326 → be8c9ff.

**Comment by mrunalp** [comment]
LGTM. @liangchenye PTAL.

**Comment by liangchenye** [comment]
LGTM

**Pull request merged**
