### PR TITLE
Only set boolean parameters if they are passed as flags

### PR DESCRIPTION
**Pull request by mrunalp**
Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by liangchenye** [comment]
I think we do not need to check the bool flag before use it. If a bool flag is not set, context.Bool will return `false` as a default.

**Comment by mrunalp** [comment]
This is for when we set a bool to true in a template and then try to use it.
For e.g.
```
# Create a config.json to be used as template with terminal true
$ ocitools generate --tty
$ mv config.json config.json.template

# Try using that template to create another config.json
# Without this PR, the terminal will be set to false even though it wasn't specified.
$ ocitools generate --args /bin/bash --template config.json.template

**Comment by liangchenye** [comment]
Make sense.
LGTM

**Comment by mrunalp** [comment]
Thanks!

**Pull request merged**
