### PR TITLE
generate: fix mount-cgroups bug

### PR DESCRIPTION
**Pull request by Mashimiao**
Signed-off-by: Ma Shimiao <mashimiao.fnst@cn.fujitsu.com>

### CODE REVIEW

**Comment by wking** [comment]
c4fb2c04 looks good to me.

**Comment by Mashimiao** [comment]
ping @liangchenye  @mrunalp

**Comment by liangchenye** [comment]
LGTM

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
