### PR TITLE
Add default value for `--path` opt of `validate`

### PR DESCRIPTION
**Pull request by hmeng-19**
This PR is for #91 .

### CODE REVIEW

**Comment by mrunalp** [comment]
@liangchenye WDYT?

**Comment by liangchenye** [comment]
LGTM

**Comment by liangchenye** [comment]
@mrunalp  remove my previous LGTM

@hmeng-19 would you like to change README.md by adding 'Bundle validation succeed.'

**Comment by hmeng-19** [comment]
@liangchenye , do you mean the successful output of `ocitools validate` should be `Bundle validation succeed`, right? 
If that is the case, we may also need to modify `validate.go` reflect the change. right?

**Comment by liangchenye** [comment]
Yes, I just notice the process of bundle validation is invisible to users. The previous README.md does not provide useful information. Since you've changed REAMDE.me in this commit, it will be a good improvement if you add logs like runtimetest(https://github.com/opencontainers/ocitools/blob/master/cmd/runtimetest/main.go#L38).

**Comment by wking** [comment]
On Thu, Jun 02, 2016 at 07:01:09PM -0700, hmeng-19 wrote:
> @liangchenye , do you mean the successful output of `ocitools
> validate` should be `Bundle validation succeed`, right?

I like my command line tools to exit zero and print nothing on success
(if they have nothing to say beyond “everything is fine”).  If we're
adding noise to the output (stderr?), can we at least put it behind a
--log-level=[error|info|debug] flag or similar?

**Comment by wking** [comment]
On Thu, Jun 02, 2016 at 07:29:23PM -0700, 梁辰晔 (Liang Chenye) wrote:
> Since you've changed REAMDE.me in this commit…

I like 16d4ed2b as it stands and am not wild about the logging change.
Can we bump the logging discussion to a follow-up PR?

**Comment by liangchenye** [comment]
@wking yes, that is a follow-up PR. (with --log-level)
@hmeng-19  without the big log changes, you don't need to change validation.go, it already exists.
If a config.json passes the validation test, 'Bundle validation succeeded' is a nature output.
I prefer to have it as it reflecting the running status.

**Comment by wking** [comment]
On Thu, Jun 02, 2016 at 11:20:31PM -0700, 梁辰晔 (Liang Chenye) wrote:
> @hmeng-19 without the big log changes, you don't need to change
> validation.go, it already exists.  If a config.json passes the
> validation test, 'Bundle validation succeeded' is a nature output.
> I prefer to have it as it reflecting the running status.

I don't think this PR or #91 have anything to do with a
printed-on-success message.  This is just about “don't require folks
to set --path”.  And the error message being removed from the README
suggests that current-directory default does not already exist.

**Comment by liangchenye** [comment]
README.md tells how ocitools works.
It is right to remove the error message, but I think we should add other message back.
Running "./ocitools validate" with this commit merged, it will either tells "Bundle valiation succeeded" or something is wrong, there is no blank result.

**Comment by wking** [comment]
On Fri, Jun 03, 2016 at 12:10:59AM -0700, 梁辰晔 (Liang Chenye) wrote:
> It is right to remove the error message, but I think we should add
> other message back.  Running "./ocitools validate" with this commit
> merged, it will either tells "Bundle valiation succeeded" or
> something is wrong, there is no blank result.

Ah.  I'd read your previous comments as:

  We should update validate.go to print “Bundle validation succeeded.”
  on success, and then reflect that change in the README.

What you're actually saying is:

  validate.go already prints “Bundle validation succeeded.”
  on success.  We should reflect that change in the README.

That sounds good to me.

**Comment by hmeng-19** [comment]
@liangchenye , please give it a new look.

**Comment by liangchenye** [comment]
LGTM
@mrunalp

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
