### PR TITLE
rootfs.tar.gz: Automate construction from Gentoo's amd64 stage3

### PR DESCRIPTION
**Pull request by wking**
Cross-posted from mrunalp/ocitools#17.

Details in the commit messages (and docs in the README commit), but
this pulls a statically-linked BusyBox from Gentoo's amd64 stage3 and
uses it to seed the tarball. We can also easily grab other things
from that stage3 if we need them later, but things like libapparmor
(that aren't in Gentoo's stage3) will need a different approach.

### CODE REVIEW

**Comment by mrunalp** [comment]
I followed the guide. It probably needs more info to setup the keys ;)

```
[root@localhost ocitools]# make rootfs.tar.gz                                                                                                                
./get-stage3.sh
--2016-01-20 17:00:05--  http://distfiles.gentoo.org/releases/amd64/autobuilds/latest-stage3.txt
Resolving distfiles.gentoo.org (distfiles.gentoo.org)... 64.50.233.100, 64.50.236.52, 140.211.166.134, ...
Connecting to distfiles.gentoo.org (distfiles.gentoo.org)|64.50.233.100|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 784 [text/plain]
Saving to: ‘STDOUT’

-                                       100%[============================================================================>]     784  --.-KB/s    in 0s      

2016-01-20 17:00:06 (48.8 MB/s) - written to stdout [784/784]

touch downloads/stage3-amd64-*.tar.bz2
gpg --verify downloads/stage3-amd64-current.tar.bz2.DIGESTS.asc
gpg: Signature made Thu 14 Jan 2016 09:00:11 PM EST using RSA key ID 2D182910
gpg: Can't check signature: public key not found
Makefile:15: recipe for target 'rootfs/bin/busybox' failed
make: *** [rootfs/bin/busybox] Error 2
```

**Comment by wking** [comment]
On Wed, Jan 20, 2016 at 02:02:20PM -0800, Mrunal Patel wrote:
> I followed the guide. It probably needs more info to setup the keys ;)
> …
> gpg --verify downloads/stage3-amd64-current.tar.bz2.DIGESTS.asc
> gpg: Signature made Thu 14 Jan 2016 09:00:11 PM EST using RSA key ID 2D182910
> gpg: Can't check signature: public key not found

You need:

  $ gpg --search 0x2D182910

and then import the key.  Until your web-of-trust reaches out to the
Gentoo Rel-Eng team, verification will give you:

  gpg: WARNING: This key is not certified with a trusted signature!
  gpg:          There is no indication that the signature belongs to the owner.

but that's not fatal (and I'm not sure how you'd make it fatal even if
you wanted it to be).  Does that fall under “basic GnuPG usage”, or is
it worth writing up in docs here?

**Comment by mrunalp** [comment]
@wking I think we should just add to the steps so it is easy for someone to rebuild the rootfs.
I tested it out and it the rootfs works with the runtime tests and runc.

**Comment by wking** [comment]
On Wed, Jan 20, 2016 at 02:25:49PM -0800, Mrunal Patel wrote:
> @wking I think we should just add to the steps so it is easy for
> someone to rebuild the rootfs.

I just pushed a328eef5 with more docs around this.  Let me know if
that is what you were looking for (and feel free to push some fixup
commits where I can get them if it wasn't ;).

**Comment by mrunalp** [comment]
LGTM

**Pull request merged**
