### PR TITLE
README: Punt detailed command description to the man pages

### PR DESCRIPTION
**Pull request by wking**
This makes it easier to get a project overview from the README, and
avoids the tedium of keeping parallel sets of detailed docs up to
date.

### CODE REVIEW

**Comment by liangchenye** [comment]
It looks much better. 
TODO: We can add the runtime test description to the `Testing OCI runtimes` part just like what you to do generete and validate.

LGTM

**Comment by wking** [comment]
On Wed, Apr 27, 2016 at 11:55:42PM -0700, 梁辰晔 (Liang Chenye) wrote:
“TODO: We can add the runtime test description to the `Testing OCI
runtimes` part just like what you to do generete and validate.”

I think it would be better to make test_runtime.sh a first-class
citizen (‘ocitools certify’?) with a man page and everything.  But
that seemed out of scope for this PR ;).

**Comment by liangchenye** [comment]
Yes. And we need to discuss with @zenlinTechnofreak about his PR and his busy these day aroud.

**Comment by mrunalp** [comment]
@wking Agree that we need to convert the script into a first class option. Just needs to be done :)
LGTM

**Pull request merged**
